name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.0'
    env:
      MONGO_ATLAS_API_URL: ${{ secrets.MONGO_ATLAS_API_URL }}
      MONGO_ATLAS_API_KEY: ${{ secrets.MONGO_ATLAS_API_KEY }}
      MONGO_DATABASE_NAME: ${{ secrets.MONGO_DATABASE_NAME }}
      MONGO_COLLECTION_NAME: ${{ secrets.MONGO_COLLECTION_NAME }}
      MONGO_DATASOURCE_NAME: ${{ secrets.MONGO_DATASOURCE_NAME }}

    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Rubocop
      run: bundle exec rubocop
